# Generated by Django 5.2 on 2025-04-23 14:59

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("address", models.TextField(verbose_name="Endereço")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Unidade Operacional",
                "verbose_name_plural": "Unidades Operacionais",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matrícula"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("address", models.TextField(verbose_name="Endereço")),
                (
                    "weekly_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=44.0,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Carga Horária Semanal",
                    ),
                ),
                (
                    "is_manager",
                    models.BooleanField(default=False, verbose_name="É Gestor"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "operational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hr.operationalunit",
                        verbose_name="Unidade Operacional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
                "ordering": ["registration_number"],
            },
        ),
        migrations.CreateModel(
            name="OvertimeBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DurationField(
                        default=datetime.timedelta(0),
                        help_text="Saldo em horas (positivo ou negativo)",
                        verbose_name="Saldo",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.employee",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco de Horas",
                "verbose_name_plural": "Bancos de Horas",
                "ordering": ["employee__registration_number"],
            },
        ),
        migrations.CreateModel(
            name="TimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Data/Hora")),
                (
                    "record_type",
                    models.CharField(
                        choices=[("IN", "Entrada"), ("OUT", "Saída")],
                        max_length=3,
                        verbose_name="Tipo de Registro",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hr.employee",
                        verbose_name="Funcionário",
                    ),
                ),
                (
                    "operational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hr.operationalunit",
                        verbose_name="Unidade Operacional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Ponto",
                "verbose_name_plural": "Registros de Ponto",
                "ordering": ["-timestamp"],
            },
        ),
    ]
